version: '2.1'

services:
  be:
    build:
      context: .
    restart: always
    container_name: tutorial_backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PW: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8081:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: tutorial_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: tutorial_pma
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_vol:
    driver: local
